"use client";

import Header from "../../components/Header";
import Footer from "../../components/footer";
import Lines from "../../components/lines";
import ScrollToTop from "../../components/scrollToTop";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import ToasterContext from "@/context/ToastContent";
const inter = Inter({ subsets: ["latin"] });

//import "../globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-dark ${inter.className}`}>
        <ThemeProvider enableSystem={false} attribute="class" defaultTheme="light">
          <Lines/>
          <Header/>
          <ToasterContext/>
          {children}
          <Footer/>
          <ScrollToTop/>
        </ThemeProvider>
      </body>
    </html>
  );
}
