# Generated by Django 5.1.3 on 2024-11-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_sector_is_featured_sector_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sector', to='Task.sector', verbose_name='Sector'),
        ),
    ]
