# Generated by Django 5.1.3 on 2025-03-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Task', '0005_rename_user_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to='Accounts.assignees', verbose_name='Assigned To'),
        ),
    ]
